all: client server

sak:
	gcc -Wall sak_uptimeClient.c -o client
	gcc -Wall sak_uptimeServer.c -o server

client: ruptimeClient.c
	gcc -Wall ruptimeClient.c -o client

server: ruptimeServer.c
	gcc -Wall ruptimeServer.c -o server
